<?php

namespace AppBundle\Repository;

/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D20ClassRepository extends \Doctrine\ORM\EntityRepository
{
}
