<?php

namespace AppBundle\Repository;

/**
 * DnDCharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D20CharacterRepository extends \Doctrine\ORM\EntityRepository
{
}
