AppBundle\Entity\D20Character:
    type: entity
    table: d20_character
    repositoryClass: AppBundle\Repository\D20CharacterRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            column: name
        deityName:
            type: string
            length: 255
            column: deity_name
        age:
            type: integer
            column: age
        size:
            type: integer
            column: size
        abilitySTR:
            type: integer
            column: ability_str
        abilityDEX:
            type: integer
            column: ability_dex
        abilityCON:
            type: integer
            column: CON
        abilityINT:
            type: integer
            column: ability_int
        abilityWIS:
            type: integer
            column: ability_wis
        abilityCHA:
            type: integer
            column: ability_cha
        savingFortitude:
            type: integer
            column: ability_fortitude
        savingReflex:
            type: integer
            column: ability_reflex
        savingWill:
            type: integer
            column: ability_will
        baseAttack:
            type: integer
            column: base_attack
        spellResistance:
            type: integer
            column: spell_resistance
        hitPoints:
            type: integer
            column: hit_points
        armorClass:
            type: integer
            column: armor_class
        initiative:
            type: integer
            column: initiative
        speed:
            type: integer
            column: speed
        damageReduction:
            type: integer
            column: damage_reduction
    lifecycleCallbacks: {  }
    manyToOne:
        playerId:
            targetEntity: D20Player
            joinColumn:
                name: player_id
                referencedColumnName: id
        raceId:
            targetEntity: D20Race
            joinColumn:
                name: race_id
                referencedColumnName: id
        classId:
            targetEntity: D20Class
            joinColumn:
                name: class_id
                referencedColumnName: id
