AppBundle\Entity\D20Player:
    type: entity
    table: d20_player
    repositoryClass: AppBundle\Repository\D20PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
