AppBundle\Entity\OAuthAccessToken:
    type: entity
    table: o_auth_access_token
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            length: 255
            column: token
        expiresAt:
            type: integer
            column: expires_at
        scope:
            type: string
            length: 255
            column: scope
    manyToOne:
            userId:
                targetEntity: D20Player
                joinColumn:
                    name: user_id
                    referencedColumnName: id
            clientId:
                targetEntity: OAuthClient
                joinColumn:
                    name: client_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }
